#!/usr/bin/env python3
"""Render docs/index.html from docs/index.template.html.

The template embeds real files from the repository with `{{include:<path>}}`.
Rendering rather than hand-copying is what keeps the published guidance and the
pipelines it documents from drifting apart: change a pipeline, re-run this, and
the page changes with it.

    python3 tools/build_docs.py           # write docs/index.html
    python3 tools/build_docs.py --check   # fail if it is out of date

`--check` is what CI runs.
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATE = REPO_ROOT / "docs" / "index.template.html"
OUTPUT = REPO_ROOT / "docs" / "index.html"

INCLUDE = re.compile(r"\{\{include:(?P<path>[^}]+)\}\}")

BANNER = (
    "<!-- Generated by tools/build_docs.py from docs/index.template.html. "
    "Edit the template, not this file. -->\n"
)


def render(template_text: str) -> str:
    missing: list[str] = []

    def substitute(match: re.Match[str]) -> str:
        relative = match.group("path").strip()
        target = REPO_ROOT / relative
        if not target.is_file():
            missing.append(relative)
            return match.group(0)
        # Escaped, and with trailing whitespace stripped so the rendered <pre>
        # does not end on a blank line.
        return html.escape(target.read_text(encoding="utf-8").rstrip("\n"))

    rendered = INCLUDE.sub(substitute, template_text)

    if missing:
        raise SystemExit(
            "Template references files that do not exist:\n  "
            + "\n  ".join(sorted(set(missing)))
        )

    return BANNER + rendered


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if docs/index.html differs from the rendered template",
    )
    args = parser.parse_args()

    if not TEMPLATE.is_file():
        raise SystemExit(f"Template not found: {TEMPLATE}")

    rendered = render(TEMPLATE.read_text(encoding="utf-8"))

    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
        if current != rendered:
            print(
                "docs/index.html is out of date.\n"
                "Run: python3 tools/build_docs.py",
                file=sys.stderr,
            )
            return 1
        print("docs/index.html is up to date.")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(REPO_ROOT)} ({len(rendered):,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
